name: Merge Flow Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-merge-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge flow
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          HEAD_BRANCH=${{ github.head_ref }}
          
          echo "PR from $HEAD_BRANCH to $BASE_BRANCH"
          
          # Enforce merge flow: development -> staging -> main
          if [[ "$BASE_BRANCH" == "main" && "$HEAD_BRANCH" != "staging" ]]; then
            echo "❌ ERROR: Direct merges to main are only allowed from staging branch"
            echo "Please follow the merge flow: development -> staging -> main"
            exit 1
          fi
          
          if [[ "$BASE_BRANCH" == "staging" && "$HEAD_BRANCH" != "development" ]]; then
            echo "⚠️  WARNING: Merges to staging should typically come from development"
            echo "Allowing for hotfixes, but please ensure this is intentional"
          fi
          
          echo "✅ Merge flow validation passed"

  # Label PR based on target branch
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Label PR
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [];
            const baseBranch = context.payload.pull_request.base.ref;
            
            if (baseBranch === 'main') {
              labels.push('production');
              labels.push('needs-approval');
            } else if (baseBranch === 'staging') {
              labels.push('staging');
            } else if (baseBranch === 'development') {
              labels.push('development');
            }
            
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: labels
              });
            }