site_name: Big Mood Detector
site_description: Clinical-grade mood episode detection from wearable data
site_author: Big Mood Detector Contributors
site_url: https://clarity-digital-twin.github.io/big-mood-detector
repo_url: https://github.com/Clarity-Digital-Twin/big-mood-detector
repo_name: Clarity-Digital-Twin/big-mood-detector
copyright: Copyright &copy; 2025 Big Mood Detector Contributors

# Theme configuration
theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  
  icon:
    repo: fontawesome/brands/github
    logo: material/heart-pulse

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]'

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Social links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Clarity-Digital-Twin/big-mood-detector
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/big-mood-detector/

# Navigation
nav:
  - Home: ../README.md
  
  - Getting Started:
    - Quick Start: user/QUICK_START_GUIDE.md
    - User Guide: user/README.md
    - Application Workflow: user/APPLICATION_WORKFLOW.md
    - Setup Guides:
      - Installation: setup/SETUP_GUIDE.md
      - Data Setup: setup/DATA_SETUP_GUIDE.md
      - Docker Setup: setup/DOCKER_SETUP_GUIDE.md
      - PC Migration: setup/PC_MIGRATION_CHECKLIST.md
  
  - Architecture:
    - Overview: developer/ARCHITECTURE_OVERVIEW.md
    - Dual Pipeline: developer/DUAL_PIPELINE_ARCHITECTURE.md
    - Model Weights: developer/MODEL_WEIGHT_ARCHITECTURE.md
    - Data Processing: developer/DATA_DOSSIER.md
    - XML Optimization: architecture/xml_optimization_solution.md
  
  - Clinical:
    - Overview: clinical/README.md
    - Requirements: clinical/CLINICAL_REQUIREMENTS_DOCUMENT.md
    - Clinical Dossier: clinical/CLINICAL_DOSSIER.md
  
  - API Reference:
    - Overview: developer/API_REFERENCE.md
    - REST Endpoints:
      - Health: api/health.md
      - Features: api/features.md
      - Predictions: api/predictions.md
      - Labels: api/labels.md
      - Clinical: api/clinical.md
  
  - ML Training:
    - PAT Depression Training: training/PAT_DEPRESSION_TRAINING.md
    - PAT-L Paper Replication: training/PAT_L_PAPER_REPLICATION.md
    - PAT Complete Journey: training/PAT_COMPLETE_PIPELINE_JOURNEY.md
    - Training Summary: training/TRAINING_SUMMARY.md
    - Normalization Lessons: training/NORMALIZATION_LESSON_LEARNED.md
  
  - Development:
    - Developer Guide: developer/README.md
    - Git Workflow: developer/GIT_WORKFLOW.md
    - Model Integration: developer/model_integration_guide.md
    - Root Structure: developer/ROOT_STRUCTURE.md
    - Design Patterns: refactoring/DESIGN_PATTERNS_CATALOG.md
    - Changelog: refactoring/CHANGELOG.md
  
  - Operations:
    - Deployment Guide: developer/DEPLOYMENT_GUIDE.md
    - Deployment Readiness: deployment/DEPLOYMENT_READINESS.md
    - Data Files Manifest: deployment/DATA_FILES_MANIFEST.md
    - Production Notes: developer/PRODUCTION_NOTES.md
    - Security: developer/SECURITY.md
    - Performance: performance/OPTIMIZATION_TRACKING.md
  
  - Contributing:
    - Guidelines: ../CONTRIBUTING.md
    - Documentation Structure: DOCUMENTATION_STRUCTURE.md
    - AI Agent Guide: ../CLAUDE.md
  
  - Research:
    - Literature: literature/clinical_references_to_read.md