# Seoul National University XGBoost Feature Schema
# Source: Figure 3b of the paper
# Total: 36 features (12 base indexes × 3 statistics each)

features:
  # Sleep features (10 indexes × 3 = 30 features)
  - sleep_percentage_MN
  - sleep_percentage_SD
  - sleep_percentage_Z
  - sleep_amplitude_MN
  - sleep_amplitude_SD
  - sleep_amplitude_Z
  - long_num_MN
  - long_num_SD
  - long_num_Z
  - long_len_MN
  - long_len_SD
  - long_len_Z
  - long_ST_MN
  - long_ST_SD
  - long_ST_Z
  - long_WT_MN
  - long_WT_SD
  - long_WT_Z
  - short_num_MN
  - short_num_SD
  - short_num_Z
  - short_len_MN
  - short_len_SD
  - short_len_Z
  - short_ST_MN
  - short_ST_SD
  - short_ST_Z
  - short_WT_MN
  - short_WT_SD
  - short_WT_Z
  
  # Circadian features (2 indexes × 3 = 6 features)
  - circadian_amplitude_MN
  - circadian_amplitude_SD
  - circadian_amplitude_Z
  - circadian_phase_MN
  - circadian_phase_SD
  - circadian_phase_Z